name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip
        pip install --upgrade pip
        pip install buildozer cython

    - name: Install Android SDK + build-tools (FIX AIDL)
      run: |
        mkdir -p $HOME/android-sdk
        export ANDROIDSDK=$HOME/android-sdk

        sudo apt install -y wget

        cd $HOME
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip commandlinetools-linux-*.zip
        mkdir -p $ANDROIDSDK/cmdline-tools
        mv cmdline-tools $ANDROIDSDK/cmdline-tools/latest

        yes | $ANDROIDSDK/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROIDSDK \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.2"

    - name: Build APK
      run: |
        export ANDROIDSDK=$HOME/android-sdk
        export PATH=$PATH:$ANDROIDSDK/platform-tools

        buildozer android debug
