name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: kivy/buildozer:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fix permissions (IMPORTANT)
        run: |
          adduser --disabled-password builder || true
          chown -R builder:builder .

      - name: Build APK (non-root)
        run: |
          su builder -c "buildozer android debug"
